// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoFutbolDepartamental.App.Persistencia;

namespace TorneoFutbolDepartamental.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
    [Migration("20210930000330_Entidades")]
=======
    [Migration("20211013212650_Entidades")]
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs
    partial class Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Arbitro", b =>
                {
                    b.Property<int>("ArbitroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
                    b.Property<int>("GolesContra")
                        .HasColumnType("int");
=======
                    b.Property<string>("ColegioPertenece")
                        .HasColumnType("nvarchar(max)");
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int>("cntPartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("cntPartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("cntPartidosJugados")
                        .HasColumnType("int");

                    b.Property<int?>("municipioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("municipioId");
=======
                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArbitroId");
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs

                    b.ToTable("Arbitros");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", b =>
                {
                    b.Property<int>("DirectorTecnicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorTecnicoId");

                    b.ToTable("DirectoresTecnicos");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cnt_PartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("Cnt_PartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("Cnt_PartidosJugados")
                        .HasColumnType("int");

                    b.Property<int?>("DirectorTecnicoId")
                        .HasColumnType("int");

                    b.Property<int>("GolesContra")
                        .HasColumnType("int");

                    b.Property<int>("GolesFavor")
                        .HasColumnType("int");

                    b.Property<int?>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
                    b.Property<int>("maracadorEquipoVisitante")
                        .HasColumnType("int");

                    b.Property<int>("marcadorEquipoLocal")
=======
                    b.Property<int>("Puntos")
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs
                        .HasColumnType("int");

                    b.HasKey("EquipoId");

                    b.HasIndex("DirectorTecnicoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Estadio", b =>
                {
                    b.Property<int>("EstadioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadioId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Jugador", b =>
                {
                    b.Property<int>("JugadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JugadorId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
                    b.Property<int>("EquipoForeignKey")
                        .HasColumnType("int");

                    b.HasIndex("EquipoForeignKey")
                        .IsUnique()
                        .HasFilter("[EquipoForeignKey] IS NOT NULL");
=======
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs

                    b.HasKey("MunicipioId");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Partido", b =>
                {
                    b.Property<int>("PartidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ArbitroId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoLocalEquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoVisitanteEquipoId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadioId")
                        .HasColumnType("int");

                    b.Property<string>("FechaHora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Marcador")
                        .HasColumnType("int");

                    b.HasKey("PartidoId");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("EquipoLocalEquipoId");

                    b.HasIndex("EquipoVisitanteEquipoId");

                    b.HasIndex("EstadioId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Equipo", b =>
                {
<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Municipio", "municipio")
=======
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", "DirectorTecnico")
                        .WithMany()
                        .HasForeignKey("DirectorTecnicoId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Municipio", "Municipio")
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs
                        .WithMany()
                        .HasForeignKey("MunicipioId");

<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs
                    b.Navigation("municipio");
=======
                    b.Navigation("DirectorTecnico");

                    b.Navigation("Jugador");

                    b.Navigation("Municipio");
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Estadio", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Partido", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Arbitro", "Arbitro")
                        .WithMany()
                        .HasForeignKey("ArbitroId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalEquipoId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteEquipoId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId");

                    b.Navigation("Arbitro");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Estadio");
                });
<<<<<<< HEAD:TorneoFutbolDepartamental.App.Persistencia/Migrations/20210930000330_Entidades.Designer.cs

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "Equipo")
                        .WithOne("DirectorTecnico")
                        .HasForeignKey("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", "EquipoForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Jugador", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Equipo", b =>
                {
                    b.Navigation("DirectorTecnico");
                });
=======
>>>>>>> 93787db8daafa996e8308e6a8691930127ebdc74:TorneoFutbolDepartamental.App.Persistencia/Migrations/20211013212650_Entidades.Designer.cs
#pragma warning restore 612, 618
        }
    }
}
