// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoFutbolDepartamental.App.Persistencia;

namespace TorneoFutbolDepartamental.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GolesContra")
                        .HasColumnType("int");

                    b.Property<int>("GolesFavor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.Property<int>("cntPartidosEmpatados")
                        .HasColumnType("int");

                    b.Property<int>("cntPartidosGanados")
                        .HasColumnType("int");

                    b.Property<int>("cntPartidosJugados")
                        .HasColumnType("int");

                    b.Property<int?>("municipioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("municipioId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId");

                    b.ToTable("Estadios");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ArbitroId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoLocalId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoVisitanteId")
                        .HasColumnType("int");

                    b.Property<int?>("EstadioId")
                        .HasColumnType("int");

                    b.Property<string>("FechaHora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maracadorEquipoVisitante")
                        .HasColumnType("int");

                    b.Property<int>("marcadorEquipoLocal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArbitroId");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.HasIndex("EstadioId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Arbitro", b =>
                {
                    b.HasBaseType("TorneoFutbolDepartamental.App.Dominio.Persona");

                    b.Property<string>("ColegioPertenece")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Arbitro");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", b =>
                {
                    b.HasBaseType("TorneoFutbolDepartamental.App.Dominio.Persona");

                    b.Property<int>("EquipoForeignKey")
                        .HasColumnType("int");

                    b.HasIndex("EquipoForeignKey")
                        .IsUnique()
                        .HasFilter("[EquipoForeignKey] IS NOT NULL");

                    b.HasDiscriminator().HasValue("DirectorTecnico");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Jugador", b =>
                {
                    b.HasBaseType("TorneoFutbolDepartamental.App.Dominio.Persona");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EquipoId");

                    b.HasDiscriminator().HasValue("Jugador");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Equipo", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Municipio", "municipio")
                        .WithMany()
                        .HasForeignKey("municipioId");

                    b.Navigation("municipio");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Estadio", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Partido", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Arbitro", "Arbitro")
                        .WithMany()
                        .HasForeignKey("ArbitroId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId");

                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Estadio", "Estadio")
                        .WithMany()
                        .HasForeignKey("EstadioId");

                    b.Navigation("Arbitro");

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");

                    b.Navigation("Estadio");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "Equipo")
                        .WithOne("DirectorTecnico")
                        .HasForeignKey("TorneoFutbolDepartamental.App.Dominio.DirectorTecnico", "EquipoForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Jugador", b =>
                {
                    b.HasOne("TorneoFutbolDepartamental.App.Dominio.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId");

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("TorneoFutbolDepartamental.App.Dominio.Equipo", b =>
                {
                    b.Navigation("DirectorTecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
